{% set name = "RedLionfish" %}
{% set version = "0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/rosalindfranklininstitute/RedLionfish/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 47cfa25aa2602041cf66279249fbebfc995528ece465ad86f9c7f2b5f45a69a3 #v0.6

build:
  number: 0

  script: "{{ PYTHON }} ./setup_for_condabuild.py -vv install"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - pyopencl
    - reikna
    - ocl-icd-system  # [linux]

test:
  imports:
    - RedLionfishDeconv

about:
  home: https://github.com/rosalindfranklininstitute/RedLionfish
  license: Apache-2.0
  license_file: LICENSE
  summary: Richardson-Lucy deconvolution of 3D data
  description: Fast Richardson-Lucy deconvolution of 3D volume data using GPU or CPU with napari plugin.
  dev_url: https://github.com/rosalindfranklininstitute/RedLionfish

extra:
  recipe-maintainers:
    - perdigao1
