{% set name = "RedLionfish" %}
{% set version = "0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/rosalindfranklininstitute/RedLionfish/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 41149443dc338b9a8f91acde848ef37e2a590e0c9b022e447cd4326eacbc0ef6 #v0.8

build:
  number: 2

  script: "{{ PYTHON }} ./setup_for_condabuild.py -vv install"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - pyopencl
    - reikna
    - ocl-icd-system  # [linux]
    - ocl_icd_wrapper_apple  # [osx]

test:
  imports:
    - RedLionfishDeconv

about:
  home: https://github.com/rosalindfranklininstitute/RedLionfish
  license: Apache-2.0
  license_file: LICENSE
  summary: Richardson-Lucy deconvolution of 3D data
  description: Fast Richardson-Lucy deconvolution of 3D volume data using GPU or CPU with napari plugin.
  dev_url: https://github.com/rosalindfranklininstitute/RedLionfish

extra:
  recipe-maintainers:
    - perdigao1
