{% set name = "RedLionfish" %}
{% set version = "0.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/rosalindfranklininstitute/RedLionfish/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b3e99c3a46e40cad25cfae49392f71c8ede9810e228261c64f141ce444f08de #v0.10

build:
  number: 1

  script: "{{ PYTHON }} ./setup_for_condabuild.py -vv install"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - pyopencl
    - reikna
    - ocl-icd-system  # [linux]
    - ocl_icd_wrapper_apple  # [osx]

test:
  imports:
    - RedLionfishDeconv

about:
  home: https://github.com/rosalindfranklininstitute/RedLionfish
  license: Apache-2.0
  license_file: LICENSE
  summary: Richardson-Lucy deconvolution of 3D data
  description: Fast Richardson-Lucy deconvolution of 3D volume data using GPU or CPU with napari plugin.
  dev_url: https://github.com/rosalindfranklininstitute/RedLionfish

extra:
  recipe-maintainers:
    - perdigao1
