{% set name = "RedLionfish" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rosalindfranklininstitute/RedLionfish/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1a6991a32d62ca5f27481ecd7332e0a8a080a21dd7f82ccdd34949cf33332292 #v0.6

build:
  number: 0

  script: {{ PYTHON }} ./setup_for_condabuild.py -vv install

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - pyopencl
    - reikna
    - ocl-icd-system  # [linux]

test:
  imports:
    - RedLionfishDeconv

about:
  home: https://github.com/rosalindfranklininstitute/RedLionfish
  license: Apache-2.0
  license_file: LICENSE
  summary: Richardson-Lucy deconvolution of 3D data
  description: Fast Richardson-Lucy deconvolution of 3D volume data using GPU or CPU with napari plugin.
  dev_url: https://github.com/rosalindfranklininstitute/RedLionfish

extra:
  recipe-maintainers:
    - perdigao1
